### ISSUE TITLE
Set server in backup mode

### ISSUE THREAD

**Issue by punkeel** [kamermans/HAProxyAPI#1]
Hello,

Would this be possible? Just asking. I'll try on my own for now

**Comment by kamermans** [comment]
I'm not sure how to do this, but if it's available in the underlying API it should work from this PHP API.  I'll take a look at it a little later tonight.

**Comment by punkeel** [comment]
I wasn't expecting a reply right now, but thanks!

Looks like to be impossible to achieve. I'll stick with a manual system, then ... :(

**Comment by kamermans** [comment]
You can thank the Slack integration :)
